language: generic
sudo: required
service:
  - docker
before_install:
  - docker build -t wkrause13/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true wkrause13/react-test npm test

after_success:
  - docker build -t wkrause13/multi-client ./client
  - docker build -t wkrause13/multi-server ./server
  - docker build -t wkrause13/multi-nginx ./nginx
  - docker build -t wkrause13/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push wkrause13/multi-client
  - docker push wkrause13/multi-server
  - docker push wkrause13/multi-nginx
  - docker push wkrause13/multi-worker
